#!/bin/sh
#script by Aaron Moore (Kevna), all rights reserved
#compiles LaTeX source files to PDF using pdflatex
#for 3 iterations or number specified by -n

max=3
#get command line arguments
while [[ $1 ]]; do
	case "$1" in
	"-h" | "-?")
		echo "this script compiles a LaTeX file multiple times using pdflatex"
		echo "usage is comptex filename <option>"
		echo "where \"filename\" is one or more files to be compiled into pdf"
		echo "and <option> may be zero or more switches from:"
		echo -e "\t-n #\tcompile document # times"
		echo -e "\t-h\tdisplay this help message and exit"
		echo "multiple filenames and options should be space-delimited"
		exit 0
		;;
	"-n")
		shift
		if [[ $1 =~ ^[0-9]+$ ]]; then
			max=$1
		else
			echo "$1 is not a valid number of iterations" >&2
			echo "resorting to default" >&2
		fi
		;;
	*)
		if [ -f "$1" ]; then
			files="$files $1"
		else
			echo "$1 was not recognised as an argument or filename" >&2
		fi
		;;
	esac
	shift
done

if [[ "$files" == "" ]]; then
	#echo error message into STDERR (file descriptor 2)
	echo "usage is comptex filename <option>" >&2
	exit 1
fi
for filename in $files; do
	for i in $(seq 1 $max); do
		pdflatex -halt-on-error $filename 2> texerr.log 1>/dev/null
		if [[ $? == 0 ]]; then
			echo "$filename written $i times"
			rm texerr.log
		else
			cat texerr.log >&2
			echo "failed to write $filename at iteration $i" >&2
			echo "transcript available at $(pwd)/texerr.log" >&2
			exit 1
		fi
	done
done
exit 0

